services:
  - type: web
    name: my-nextjs-express-app
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../backend && npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production
